name: "CI"
on:
  pull_request:
  push:
    branches:
      - nixos-unstable
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: write-all
jobs:
  generate-nixconf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wimpysworld/nothing-but-nix@main
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        extra-conf: |
          experimental-features = nix-command flakes pipe-operators
    - run: nix run .#gcn > nix.conf
    - uses: actions/upload-artifact@v4
      with:
        name: nix-conf
        path: nix.conf
  swayfx:
    runs-on: ubuntu-latest
    needs: [ generate-nixconf ]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: wimpysworld/nothing-but-nix@main
    - uses: actions/download-artifact@v4
      with:
        name: nix-conf
    - name: Read nix.conf
      id: nix
      run: |
        {
          echo 'CONF<<EOF'
          cat nix.conf
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        extra-conf: |
          ${{ steps.nix.outputs.CONF }}
    - uses: cachix/cachix-action@master
      with:
        name: fmcachix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipAddingSubstituter: true
    - name: Build
      run: nix build .#swayfx --verbose
    - name: Info
      run: nix path-info -Sh ./result
    - run: nix-collect-garbage -d
  gnome-session:
    runs-on: ubuntu-latest
    needs: [ generate-nixconf ]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: wimpysworld/nothing-but-nix@main
    - uses: actions/download-artifact@v4
      with:
        name: nix-conf
    - name: Read nix.conf
      id: nix
      run: |
        {
          echo 'CONF<<EOF'
          cat nix.conf
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        extra-conf: |
          ${{ steps.nix.outputs.CONF }}
    - uses: cachix/cachix-action@master
      with:
        name: fmcachix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipAddingSubstituter: true
    - name: Build
      run: nix build .#gnome-session --verbose
    - name: Info
      run: nix path-info -Sh ./result
    - run: nix-collect-garbage -d
  nixos:
    runs-on: ubuntu-latest
    needs:
    - generate-nixconf
    - swayfx
    - gnome-session
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: wimpysworld/nothing-but-nix@main
      with:
        hatchet-protocol: 'rampage'
        root-safe-haven: '3072'   # Reserve 3GB on the / filesystem
        mnt-safe-haven: '2048'    # Reserve 2GB on the /mnt filesystem
    - name: "Check current branch"
      run: git branch
    - uses: actions/download-artifact@v4
      with:
        name: nix-conf
    - name: Read nix.conf
      id: nix
      run: |
        {
          echo 'CONF<<EOF'
          cat nix.conf
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        extra-conf: |
          ${{ steps.nix.outputs.CONF }}
    - name: Build
      run: nix run nixpkgs#nixos-rebuild -- build --flake .#default --verbose
    - name: Info
      run: nix path-info -Sh ./result

  auto-merge:
    needs: [ nixos ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && !cancelled() && success() && !contains(needs.*.result, 'skipped') }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup git
      run: |
        git config --global user.name 'fmway'
        git config --global user.email 'fm18lv@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Enable auto-merge
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: ${{ github.head_ref }}
      run: |
        if [[ "${BRANCH}" != "nixos-unstable" ]]; then
          gh pr merge --auto --merge "$PR_URL" -d
        else
          gh pr merge --auto --merge "$PR_URL"
        fi

# TODO add readme generator
# TODO ci for nixvim
