name: Auto Pull Request
on:
  schedule:
  - cron: "0 0,6,12,18 * * *"
  - cron: "0 */6 * * *"

permissions: write-all

jobs:
  lockfile:
    runs-on: [ubuntu-latest]
    if: ${{ github.event_name != 'pull_request' && github.ref_name != 'nightly-update' && (github.event.head_commit.author.name == 'fmway' || (github.event_name == 'schedule' && github.event.schedule == '0 0,6,12,18 * * *') || github.event_name == 'workflow_dispatch') }}
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        extra-conf: ${{ env.nix-conf }}
    - uses: DeterminateSystems/update-flake-lock@v25
      name: Update flake.lock
      with:
        branch: nightly-update
        token: ${{ secrets.GH_TOKEN }}
        git-author-name: 'little fmway'
        git-author-email: 'fm18lv@gmail.com'
        git-committer-name: 'little fmway'
        git-committer-email: 'fm18lv@gmail.com'
        commit-msg: 'chore(lockfile): update flake.lock'
        pr-title: 'chore(lockfile): update flake.lock'
        pr-labels: |
          dependencies
          automated

  update-stubby:
    if: ${{ github.event.schedule == '0 */6 * * *' }}
    runs-on: [ "ubuntu-latest" ]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Setup git
      run: |
        git config --global user.name 'little fmway'
        git config --global user.email 'fm18lv@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        extra-conf: experimental-features = nix-command flakes auto-allocate-uids configurable-impure-env pipe-operators
    - run: nix run .#updateStubbyCert
    - name: Check Updates
      id: check
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      run: |
        if [ -n "$(git status --short)" ]; then
          git add -A
          git commit -m "chore(systems): update certs dns"
          git checkout -B stubby-updater
          git push origin stubby-updater --force
          if [ -z "$(git diff origin/stubby-updater origin/nixos-unstable)" ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "skip=true" >> "$GITHUB_OUTPUT"
        fi
    - name: Pull Request
      if: '!steps.check.outputs.skip'
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      run: |
        gh pr create --title "chore(system): update certs dns" --body "" -l "automated" -l "dependencies" --head stubby-updater --base nixos-unstable
